JWT_SECRET = "ABCD1234!"
JWT_ALGORITHM = "HS256"
AZURE_STORAGE_KEY = "AaUEZHA1CRFHNHNKJvSH9H2uIurYVedFzbWhBgqVTKTGNZa28gSKMM5xfy7Ls8w0r5Zf1TZC81IvnNgSxOOG1Q=="
AZURE_STORAGE_ACCESS = "DefaultEndpointsProtocol=https;AccountName=themestorage;AccountKey=AaUEZHA1CRFHNHNKJvSH9H2uIurYVedFzbWhBgqVTKTGNZa28gSKMM5xfy7Ls8w0r5Zf1TZC81IvnNgSxOOG1Q==;EndpointSuffix=core.windows.net"
EXCEPT_PATH_LIST = ["/", "/openapi.json"]
EXCEPT_PATH_REGEX = "^(/docs|/redoc|/api/auth)"
MAX_API_KEY = 3
MAX_API_WHITELIST = 10
